### ISSUE TITLE
Define algorithm for generated hosts when there are multiple rule blocks in ingress

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kcp-glbc#235]
Currently if an ingress is created with multiple rules blocks, each rule block will receive the same GLBC generated host. This wont work well if there are common paths between these blocks. 

For each unique custom host we need to generate a unique managed host.  See example below. 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-domain
spec:
  rules:
    - host: foo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpecho-a
                port:
                  number: 80
    - host: guid1.hcpapps.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpecho-a
                port:
                  number: 80                  
    - host: bar.com 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpecho-b
                port:
                  number: 80
    - host: guid2.hcpapps.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpecho-b
                port:
                  number: 80

```
**Same custom domain multiple ingresses in the same namespace**

The same managed host should be used for each ingress within a single namespace that uses that custom domain:
We cannot support the same custom domain being used across different namespaces as we cannot guarantee that the workloads will all end up on the same cluster 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-domain-1
spec:
  rules:
    - host: foo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpecho-a
                port:
                  number: 80
    - host: guid1.hcpapps.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpecho-a
                port:
                  number: 80              
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-domain-2
spec:
  rules:
    - host: foo.com
      http:
        paths:
          - path: /apps
            pathType: Prefix
            backend:
              service:
                name: httpecho-b
                port:
                  number: 80
    - host: guid1.hcpapps.net
      http:
        paths:
          - path: /apps
            pathType: Prefix
            backend:
              service:
                name: httpecho-b
                port:
                  number: 80       

```

**Empty Hosts**
- We should reject the ingress if there are two empty hosts in an ingress as this is not valid in cluster.  
- We should continue to generate a unique managed host per empty host
- Two ingresses with empty hosts should always get different managed hosts

Open Question
- if a an empty host  in an ingress is replaced with a custom host what should the behaviour be
- The managed host stays the same and that becomes the CNAME and any other ingress created within that namespace with the same custom domain will receive that managed host
