### ISSUE TITLE
Consolidate ingress status into a single annotation

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kcp-glbc#277]
**What**

We currently have several annotations. We create a status block that we serialize into a single annotation. We can then use this status block as a single point to add and check the condition of the ingress and our functionality. 

something like:
```
conditions:
    - lastTransitionTime: "2019-10-22T16:29:24Z"
      status: "True"
      message: "ingress accepted"
      reason: "..." 
      type: Ready
    - lastTransitionTime: "2019-10-22T16:29:24Z"
      status: "True"
      type: TLSReady
      message: "lets encrypt cert provisoned"
      reason: "..."
    - lastTransitionTime: "2019-10-22T16:29:24Z"
      status: "True"
      type: DNSReady
      message: "DNS records updated"
      reason: "..."
managedHost: 1234.hcpapps.net


```

to do this we should build out a status package. It should be possible for this status package to add status in the future to OpenShift routes and also Gateway API HTTPRoutes
